#pragma once

enum class Event {
  // Background Events
  BG_DEFAULT_SWITCH,
  BG_SHADOW_SWITCH,
  BG_CLEAR,

  // Page Switching
  MENU_MENU_SWITCH,
  LEVEL_PAGE_SWITCH,
  GAME_PAGE_SWITCH,
  GO_BACK_SWITCH,
  ABOUT_PAGE_SWITCH,
  PAUSE_PAGE_SWITCH,
  WIN_PAGE_SWITCH,
  LOSE_PAGE_SWITCH,
};
